/*
 * Copyright (c) 2018-2020 vChain, Inc. All Rights Reserved.
 * This software is released under GPL3.
 * The full license information can be found under:
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 */

package cicontext

// CIEnvWhiteList contains gitlab github and jenkins common environment variables
var CIEnvWhiteList = map[string]int{
	// gitlab, github
	"CI": 1,
	// gitlab
	"CI_JOB_ID":                 1,
	"CI_COMMIT_SHA":             1,
	"CI_COMMIT_SHORT_SHA":       1,
	"CI_COMMIT_REF_NAME":        1,
	"CI_REPOSITORY_URL":         1,
	"CI_COMMIT_TAG":             1,
	"CI_JOB_NAME":               1,
	"CI_JOB_STAGE":              1,
	"CI_JOB_MANUAL":             1,
	"CI_JOB_TRIGGERED":          1,
	"CI_JOB_TOKEN":              1,
	"CI_PIPELINE_ID":            1,
	"CI_PIPELINE_IID":           1,
	"CI_PAGES_DOMAIN":           1,
	"CI_PAGES_URL":              1,
	"CI_PROJECT_ID":             1,
	"CI_PROJECT_DIR":            1,
	"CI_PROJECT_NAME":           1,
	"CI_PROJECT_TITLE":          1,
	"CI_PROJECT_NAMESPACE":      1,
	"CI_PROJECT_ROOT_NAMESPACE": 1,
	"CI_PROJECT_PATH":           1,
	"CI_PROJECT_URL":            1,
	"CI_REGISTRY":               1,
	"CI_REGISTRY_IMAGE":         1,
	"CI_REGISTRY_USER":          1,
	"CI_RUNNER_ID":              1,
	"CI_RUNNER_DESCRIPTION":     1,
	"CI_RUNNER_TAGS":            1,
	"CI_SERVER":                 1,
	"CI_SERVER_URL":             1,
	"CI_SERVER_HOST":            1,
	"CI_SERVER_PORT":            1,
	"CI_SERVER_PROTOCOL":        1,
	"CI_SERVER_NAME":            1,
	"CI_SERVER_REVISION":        1,
	"CI_SERVER_VERSION":         1,
	"CI_SERVER_VERSION_MAJOR":   1,
	"CI_SERVER_VERSION_MINOR":   1,
	"CI_SERVER_VERSION_PATCH":   1,
	"GITLAB_USER_EMAIL":         1,
	"GITLAB_USER_ID":            1,
	//GITHUB
	"GITHUB_WORKFLOW":    1,
	"GITHUB_RUN_ID":      1,
	"GITHUB_RUN_NUMBER":  1,
	"GITHUB_JOB":         1,
	"GITHUB_ACTION":      1,
	"GITHUB_ACTIONS":     1,
	"GITHUB_ACTOR":       1,
	"GITHUB_REPOSITORY":  1,
	"GITHUB_EVENT_NAME":  1,
	"GITHUB_EVENT_PATH":  1,
	"GITHUB_WORKSPACE":   1,
	"GITHUB_SHA":         1,
	"GITHUB_REF":         1,
	"GITHUB_HEAD_REF":    1,
	"GITHUB_BASE_REF":    1,
	"GITHUB_SERVER_URL":  1,
	"GITHUB_API_URL":     1,
	"GITHUB_GRAPHQL_URL": 1,
	// jenkins
	"BRANCH_NAME":                    1,
	"CHANGE_ID":                      1,
	"CHANGE_URL":                     1,
	"CHANGE_TITLE":                   1,
	"CHANGE_AUTHOR":                  1,
	"CHANGE_AUTHOR_DISPLAY_NAME":     1,
	"CHANGE_AUTHOR_EMAIL":            1,
	"CHANGE_TARGET":                  1,
	"BUILD_NUMBER":                   1,
	"BUILD_ID":                       1,
	"BUILD_DISPLAY_NAME":             1,
	"JOB_NAME":                       1,
	"JOB_BASE_NAME":                  1,
	"BUILD_TAG":                      1,
	"EXECUTOR_NUMBER":                1,
	"NODE_NAME":                      1,
	"NODE_LABELS":                    1,
	"WORKSPACE":                      1,
	"JENKINS_HOME":                   1,
	"JENKINS_URL":                    1,
	"BUILD_URL":                      1,
	"JOB_URL":                        1,
	"GIT_COMMIT":                     1,
	"GIT_PREVIOUS_COMMIT":            1,
	"GIT_PREVIOUS_SUCCESSFUL_COMMIT": 1,
	"GIT_BRANCH":                     1,
	"GIT_LOCAL_BRANCH":               1,
	"GIT_URL":                        1,
	"GIT_COMMITTER_NAME":             1,
	"GIT_AUTHOR_NAME":                1,
	"GIT_COMMITTER_EMAIL":            1,
	"GIT_AUTHOR_EMAIL":               1,
	"SVN_REVISION":                   1,
	"SVN_URL":                        1,
}
